import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BHAVUK
 */
public class COMPALINT1 extends javax.swing.JFrame {
String room_no , reg_no;
String sql; 
String complain;
 static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
 static final String DB_URL = "jdbc:mysql://localhost:3306/authenticate";
 // Database credentials
 static final String USER = "root";
 static final String PASS = "Bhavuk@123";
 int flag =0;
    /**
     * Creates new form COMPALINT1
     */
    public COMPALINT1() {
        initComponents();
        setSize(425,485);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FILE YOUR COMLAINT HERE >>>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 290, 50);

        ta1.setColumns(20);
        ta1.setRows(5);
        ta1.setText("Enter text when other is selected(max 100 words)");
        ta1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ta1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 400, 110);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 400, 100, 40);
        getContentPane().add(t2);
        t2.setBounds(240, 130, 120, 30);
        getContentPane().add(t1);
        t1.setBounds(240, 80, 120, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ex: 703-A");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 110, 70, 15);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ex : 17BCAN027");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 160, 110, 15);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("* Enter The Details In Block Letters");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 460, 200, 15);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROOM NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 160, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTRATION NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 170, 17);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BED", "STUDY TABLE", "CENTRE TABLE", "DOOR", "CUPBOARD", "SHELF", "OTHER" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(130, 180, 120, 30);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BED", "STUDY TABLE", "CENTRE TABLE", "DOOR", "CUPBOARD", "SHELF", "NONE", "OTHER" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(130, 230, 120, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross_button.png"))); // NOI18N
        jButton7.setToolTipText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(370, 10, 40, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_button.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.setToolTipText("BACK ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 420, 110, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black wallpaper.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, -6, 430, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
if(t1.getText().equals(""))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
else
    {
            room_no=t1.getText();
            reg_no=t2.getText();

String complain1 = (String)jComboBox1.getSelectedItem();
String complain2 = (String)jComboBox2.getSelectedItem();
if(complain2.equals("OTHER"))
    {
        complain2="OTHER("+ta1.getText()+")";
    }
complain1 = complain1 + "," + complain2;
Connection con = DriverManager.getConnection(DB_URL,"root","Bhavuk@123");
Statement stmt = con.createStatement();
ResultSet rs = stmt.executeQuery("select reg_no,room_no from student_details");
 while(rs.next()){
 String username = rs.getString("reg_no");
 String password = rs.getString("room_no");
if(username.equals(reg_no) && password.equals(room_no))
{
    flag = 1;
      break;
}
}
 if(flag == 1)
 {
PreparedStatement ps = con.prepareStatement("insert into student_complaint values('"+complain1+"',curdate(),'"+reg_no+"','NOT SOLVED','"+room_no+"','CARPENTER');");
 int status = ps.executeUpdate();
 if(status != 0 )
 { 
     flag =0;
     JOptionPane.showMessageDialog(null,"Your Complaint has been recorded");
 }
 }
 else
 {
  { 
     JOptionPane.showMessageDialog(null,"Please Enter Correct Value");
 }   
 }
 stmt.close();
 con.close();
        }
}

catch(Exception e)
{
    System.out.println(e);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new choices().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ta1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ta1FocusGained
if(ta1.getText().equals("Enter text when other is selected"))
{
    ta1.setText("");
}
else{}// TODO add your handling code here:
    }//GEN-LAST:event_ta1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COMPALINT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COMPALINT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COMPALINT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COMPALINT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COMPALINT1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
