
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BHAVUK
 */
public class warden_page_2 extends javax.swing.JFrame {
String sql;   
 static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
 static final String DB_URL = "jdbc:mysql://localhost:3306/authenticate";
 // Database credentials
 static final String USER = "root";
 static final String PASS = "Bhavuk@123";
 String ousername;
 String opassword;
 int flag =0 ;
  String fname;
 String h_name ;
 String status1,room_no,status ;
 String date , complaint;
 String reg_no , mobile ;
    /**
     * Creates new form warden_page_2
     */
    public warden_page_2() {
        initComponents();
        setSize(780,690);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SHOW COMPLAINTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 570, 210, 41);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLVED", "NOT SOLVED", "UNDER PROCESS" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(510, 510, 170, 30);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tt1.setBackground(new java.awt.Color(0, 0, 0));
        tt1.setForeground(new java.awt.Color(255, 255, 255));
        tt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FIRST NAME", "HOSTEL NAME", "ROOM NUMBER", "MOBILE NUMBER", "COMPLAINT", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, -3, 782, 350);

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TECHNITIAN", "PLUMBER", "CLEANER", "CARPENTER" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(100, 510, 160, 30);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("DATE OF COMLAINT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 380, 270, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("EX : 2020-04-21");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 480, 100, 20);

        t3.setBackground(new java.awt.Color(0, 0, 0));
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(110, 440, 130, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Print Complaints ?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 620, 100, 13);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ROOM NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 390, 190, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("EX : 703-A");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 480, 60, 20);

        t1.setBackground(new java.awt.Color(0, 0, 0));
        t1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(t1);
        t1.setBounds(540, 440, 120, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE COMPLAINTS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 620, 180, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_button.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.setToolTipText("BACK ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 630, 110, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("UPDATE COMPLAINTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(480, 570, 240, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 350, 390, 340);

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 350, 390, 340);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 350, 390, 340);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(390, 350, 390, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
 Connection con = DriverManager.getConnection(DB_URL,"root","Bhavuk@123");
 Statement stmt = con.createStatement();
 date = t3.getText();
 status1 = (String)jComboBox2.getSelectedItem();
 if(t3.getText().equals("") || t3.getText().equals(" "))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
sql="select fname,h_name,room_no,phone,complaint,status from student_details , student_complaint where student_details.reg_no=student_complaint.reg_no and head='"+status1+"' and date_of_complaint='"+date+"';";
 ResultSet rs = stmt.executeQuery(sql);
 DefaultTableModel t=(DefaultTableModel)tt1.getModel();
 t.setRowCount(0);
 while(rs.next()){
 fname = rs.getString("fname");
 h_name = rs.getString("h_name");
 room_no = rs.getString("room_no");
 mobile = rs.getString("phone");
 complaint = rs.getString("complaint");
 status = rs.getString("status");
 t.addRow(new Object[]{fname,h_name,room_no,mobile,complaint,status});
 }
 rs.close();
 stmt.close();
 con.close();

 }
 
 catch(Exception e)
{
     System.out.println(e);
 }        // TODO add your handling code here:
                                            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
   room_no = t1.getText();
   if(t1.getText().equals("") || t1.getText().equals(" "))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
   status = (String)jComboBox1.getSelectedItem();
 Connection con = DriverManager.getConnection(DB_URL,"root","toor");
 Statement stmt = con.createStatement();
sql="delete from student_complaint where status ='"+status+"' and room_num = '"+room_no+"';";
int x = stmt.executeUpdate(sql);
if(x!=0) 
{ 
     JOptionPane.showMessageDialog(null,"Status Sucessfully Deleted");
 }
else
    {
        JOptionPane.showMessageDialog(null,"please recheck your values or its format");
    }
con.close();
 stmt.close();

if(flag==1)
{
    JOptionPane.showMessageDialog(null,"enter correct room no.");
}
} 
 catch(Exception e)
 {
     System.out.println(e);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new warden_login_page().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
   room_no = t1.getText();
   if(t1.getText().equals("") || t1.getText().equals(" "))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
   status = (String)jComboBox1.getSelectedItem();
 Connection con = DriverManager.getConnection(DB_URL,"root","toor");
 Statement stmt = con.createStatement();
sql="update student_complaint set status ='"+status+"' where room_num = '"+room_no+"';";
int x = stmt.executeUpdate(sql);
if(x!=0) 
{ 
     JOptionPane.showMessageDialog(null,"Status Sucessfully Updated");
 }
else
    {
        JOptionPane.showMessageDialog(null,"please recheck your values or its format");
    }
con.close();
 stmt.close();

if(flag==1)
{
    JOptionPane.showMessageDialog(null,"enter correct room no.");
}
} 
 catch(Exception e)
 {
     System.out.println(e);
 }        // TODO add your handling code here:                                       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    try {
        tt1.print(); // TODO add your handling code here:
    } catch (PrinterException ex) {
        Logger.getLogger(warden_page_2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warden_page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warden_page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warden_page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warden_page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warden_page_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTable tt1;
    // End of variables declaration//GEN-END:variables
}
