import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BHAVUK
 */
public class worker_page_1 extends javax.swing.JFrame {

    String room_no,h_name;
    String sql;   
 static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
 static final String DB_URL = "jdbc:mysql://localhost:3306/authenticate";
 // Database credentials
 static final String USER = "root";
 static final String PASS = "Bhavuk@123";
 String status;   
 int flag = 0;
 int flag1 = 0 ;
 /**
     * Creates new form worker_page_1
     */
    public worker_page_1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(996, 564));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 480, 130, 50);
        getContentPane().add(t1);
        t1.setBounds(220, 190, 70, 30);
        getContentPane().add(t2);
        t2.setBounds(700, 170, 100, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_button.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.setToolTipText("BACK ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 10, 100, 50);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ex: 703-A");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 230, 70, 17);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ex : 17BCAN027");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(700, 210, 120, 17);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROOM NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 160, 150, 21);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REG. NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 130, 260, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STATUS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 40, 80, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLVED", "NOT SOLVED" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(460, 70, 124, 23);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross_button.png"))); // NOI18N
        jButton7.setToolTipText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(940, 10, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worker_page.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1020, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
   room_no = t1.getText();
   if(t1.getText().equals("") || t1.getText().equals(" "))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
   h_name = t2.getText();
 if(t2.getText().equals("") || t2.getText().equals(" "))
{
    JOptionPane.showMessageDialog(null,"Field cannot be left blank");
}
   status = (String)jComboBox1.getSelectedItem();
   System.out.println(status);
   System.out.println(room_no);
 Connection con = DriverManager.getConnection(DB_URL,"root","Bhavuk@123");
 Statement stmt = con.createStatement();
 ResultSet rs = stmt.executeQuery("select reg_no,room_no from student_details");
 while(rs.next()){
 String username = rs.getString("reg_no");
 String password = rs.getString("room_no");
if(username.equals(h_name) && password.equals(room_no))
{
    flag = 1;
      break;
}
}
 if(flag == 1)
 {
sql="update student_complaint set status ='"+status+"' where room_num = '"+room_no+"' and reg_no = '"+h_name+"';";
flag1 = stmt.executeUpdate(sql);
if(flag1 != 0 )
 { 
     JOptionPane.showMessageDialog(null,"Database Has Been Updated");
 }
 }
 else
 {
  {
     JOptionPane.showMessageDialog(null,"Please Enter Correct Value");
 }   
 }
 con.close();
 stmt.close();
}
 
 catch(Exception e)
{
    System.out.println(e);
    JOptionPane.showMessageDialog(null,"Please Enter Correct Value");
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new worker_login_page().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(worker_page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(worker_page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(worker_page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(worker_page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new worker_page_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
